import Head from 'next/head';
import IntroHeader from '../components/Introheader';
import { Postrecientes } from '../components/Postreciente';
import  TrabajoDestacado  from "../components/Trabajodestacado";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <IntroHeader/>
      <Postrecientes/>
      <TrabajoDestacado/>
    </div>
  );
}